# Generated by Django 4.2.6 on 2023-11-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
