# Generated by Django 4.2.6 on 2023-11-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_tag_delete_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='Tags', to='post.tag'),
        ),
    ]
