# Generated by Django 4.2.6 on 2023-11-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='binaty',
            field=models.BooleanField(default=False),
        ),
    ]
