# Generated by Django 4.2.6 on 2023-11-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_tag_binaty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='binaty',
        ),
    ]
